### ISSUE TITLE
Are you planning to submit the paper to arXiv?

### ISSUE THREAD

**Issue by alwc** [Yuanhang8605/faster-than-ctpn-a-novel-poster-text-detector#4]
Good luck with your submission to CVPR2018! By the way, have you considered submitting the paper to arXiv?

**Comment by Yuanhang8605** [comment]
@alwc Thanks for your attention. Yes, we will submit the paper to arXiv later.

**Comment by MrOCR** [comment]
@Yuanhang8605 congratulations, Pixel-Anchor is on top of the list. In many cases even 1st place for Arabic, Chinese, Japanese, Bangla & symboles.
You have done a good job.
