### ISSUE TITLE
Questions about your fapiao text detector

### ISSUE THREAD

**Issue by alwc** [Yuanhang8605/faster-than-ctpn-a-novel-poster-text-detector#5]
Hi Yuan,

Your results on your fapiao images look great! I have a few questions about the predictions.

1/ Did you use template matching on the fapiao before doing text detections?

2/ Did you train the fapiao text detector with real fapiao data, or simply synthtext + your own poster dataset?

**Comment by alwc** [comment]
xie xie ni @Yuanhang8605 !

So for the predictions in https://github.com/Yuanhang8605/faster-than-ctpn-a-novel-poster-text-detector/blob/master/test_90_rot.jpg , you first rotate the fapiao using a CNN, then you use Pixel-Anchor net to predict the bounding boxes, and at last you rotate the bounding boxes back to the original orientation?

**Comment by Yuanhang8605** [comment]
@alwc, in this simple condition, we just use the anchor part for efficiency. And we also develop a segmentation based method with for fapiao, it also perform good

**Comment by alwc** [comment]
Interesting. Let me see if I could implement Pixel-Anchor and get similar result!
